### ISSUE TITLE
Fatal Error with WP Smush Pro Compatibility Enabled

### ISSUE THREAD

**Issue by davidcommarmond** [udx/wp-stateless#325]
With WP Smush Pro installed, and WP Smush compatibility enabled, we're getting the following fatal error

```
[11-Dec-2018 15:23:15 UTC] PHP Fatal error:  Uncaught Error: Cannot access private property WP_Smush_Settings::$settings in /redacted_path_to/public_html/wp-content/plugins/wp-stateless/lib/classes/compatibility/wp-smush.php:46
Stack trace:
#0 /redacted_path_to/public_html/wp-includes/class-wp-hook.php(286): wpCloud\StatelessMedia\WPSmush->add_media_wrapper(Array, 12784)
#1 /redacted_path_to/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#2 /redacted_path_to/public_html/wp-includes/post.php(5300): apply_filters('wp_update_attac...', Array, 12784)
#3 /redacted_path_to/public_html/wp-content/plugins/wp-stateless/lib/classes/class-ajax.php(206): wp_update_attachment_metadata(12784, Array)
#4 [internal function]: wpCloud\StatelessMedia\Ajax->action_stateless_process_image(Array)
#5 /redacted_path_to/public_html/wp-content/plugins/wp-stateless/lib/classes/class-ajax.php(73): call_user_func_array(Array, Array)
#6 /redacted_path_to/public_html/wp-includes/class-wp-hook.php(286): wpCloud\StatelessMedia\Ajax->request('')
#7 /redacted_path_to/publi in /redacted_path_to/public_html/wp-content/plugins/wp-stateless/lib/classes/compatibility/wp-smush.php on line 46
```

Disabling compatibility mode resolved the error, however I'm not sure if the image gets smushed...

**Comment by av3nger** [comment]
Proposed fix #323

**Comment by antonkorotkov** [comment]
@alimuzzaman I want to test this one thoroughly. Do we have access to WP-Smush Pro plugin?

**Comment by alimuzzaman** [comment]
@antonkorotkov No we don't have.

**Comment by antonkorotkov** [comment]
@alimuzzaman OK, how we developed this compatibility then?

**Comment by alimuzzaman** [comment]
With free version then users tested it with pro version.

**Comment by antonkorotkov** [comment]
Ok. I see there only a change to possible plugin files. I'm going to close this.
