### ISSUE TITLE
Uncaught Error: Class 'GFForms' not found

### ISSUE THREAD

**Issue by dchenk** [udx/wp-stateless#330]
I'm getting this error when trying to run `wp-admin/upgrade.php` for the WP core update:
```
PHP Fatal error:  Uncaught Error: Class 'GFForms' not found in /var/www/html/wp-content/mu-plugins/wp-stateless/lib/classes/compatibility/gravity-forms.php:24
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(286): wpCloud\\StatelessMedia\\GravityForm->module_init(Array)
#1 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/html/wp-content/mu-plugins/wp-stateless/lib/classes/class-bootstrap.php(242): do_action('sm::module::ini...', Array)
#4 /var/www/html/wp-content/mu-plugins/wp-stateless/vendor/usabilitydynamics/lib-wp-bootstrap/lib/classes/class-bootstrap-plugin.php(56): wpCloud\\StatelessMedia\\Bootstrap->init()
#5 /var/www/html/wp-includes/class-wp-hook.php(286): UsabilityDynamics\\WP\\Bootstrap_Plugin->pre_init('')
#6 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#7 /var/www/html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#8 /var/www/html/wp-setting in /var/www/html/wp-content/mu-plugins/wp-stateless/lib/classes/compatibility/gravity-forms.php on line 24
```

I have WP Stateless running as a mu-plugin.

A fix would be to check if `class_exists` of 'GFForms'.

**Comment by antonkorotkov** [comment]
@alimuzzaman can you confirm that this line in safe to be without existence condition? 
https://github.com/wpCloud/wp-stateless/blob/2d16c407e09d53b7b7ccaa347bef33cdbfeb2ed3/lib/classes/compatibility/gravity-forms.php#L51

**Comment by alimuzzaman** [comment]
@antonkorotkov Yes it's safe. In that stage the plugin will be loaded. Previously the problem was we run the code without any hook/action.
But in this line is inside of a GForm hook.
