### ISSUE TITLE
Compatibility problem with Litespeed v3.2

### ISSUE THREAD

**Issue by ngxson** [udx/wp-stateless#504]
Hello, I'm recently having issue with WP Stateless after having updated Litespeed plugin to v3.2

```
[10-Jun-2020 23:54:25 UTC] PHP Fatal error:  Uncaught Error: Class 'LiteSpeed_Cache_Config' not found in (home)/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php:317
Stack trace:
#0 (home)/wp-includes/class-wp-hook.php(287): wpCloud\StatelessMedia\LSCacheWP->update_md5_and_manual_sync(991)
#1 (home)/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 (home)/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 (home)/wp-content/plugins/wp-stateless/lib/classes/class-ajax.php(193): do_action('sm:pre::synced:...', 991)
#4 [internal function]: wpCloud\StatelessMedia\Ajax->action_stateless_process_image(Array)
#5 (home)/wp-content/plugins/wp-stateless/lib/classes/class-ajax.php(75): call_user_func_array(Array, Array)
#6 (home)/wp-includes/class-wp-hook.php(287): wpCloud\StatelessMedia\Ajax-> in (home)/wp-content/plugins/wp-stateless/lib/classes/compatibility/lite-speed-cache.php on line 317
```

Seems like `LiteSpeed_Cache` and `LiteSpeed_Cache_Config` have been merged into [LiteSpeed/Base](https://github.com/litespeedtech/lscache_wp/blob/master/src/base.cls.php) since v3.0

**Comment by planv** [comment]
Hello @ngxson 

The fix will be included in the next release.
Fixed on issue [491](https://github.com/wpCloud/wp-stateless/issues/491).

**Comment by ngxson** [comment]
Good to know that. Thank you!
